###
POST http://localhost:9991/ai_suite_gemini_flash_model
Content-Type: application/json

{
  "messages": [
    {"role":  "system", "content":  "Please create a git commit in JSON response of the form { 'commitDiffs': [ {'commitDiffType': 'ADD', 'commitDiffContent': 'import lib'} ] }\n\nThis git commit will be for the following Commit message: import lib. Please include the json within delimiters ```json at the beginning and ``` at the end."}
  ]
}

###
POST http://host.docker.local:9991/ai_suite_gemini_embedding
Content-Type: application/json

{
  "to_embed":  "Try to embed this!.",
  "model": "text-embedding-004"
}

###
POST http://localhost:9991/ai_suite_gemini_embedding
Content-Type: application/json

{
  "to_embed":  "Try to embed this!.",
  "model": "text-embedding-004"
}

###
POST http://localhost:9991/ai_suite_rerank
Content-Type: application/json

{
  "rerank_body": {
    "query": "Try to embed this!.",
    "docs": [
      {
        "text": "ok",
        "metadata": {
          "first": "second"
        }
      },
      {
        "text": "another"
      }
    ]
  }
}

###
POST http://localhost:9992/ai_suite_rerank
RERANK: true
Content-Type: application/json


{
  "rerank_body": {
    "query": "Try to embed this!.",
    "docs": [
      {
        "text": "ok",
        "metadata": {
          "first": "second"
        }
      },
      {
        "text": "another"
      }
    ]
  }
}
