work_dir: "/Users/hayde/IdeaProjects/drools/model_server/work"
env_factories:
  factories:
    - factory: python_di.inject.context_builder.factory_ctx.FactoryCtx
      lazy: "False"
    - factory: python_di.inject.reflectable_ctx.ReflectableCtx
      lazy: "False"
    - factory: drools_py.inject.serialization_ctx.SerializationCtx
      lazy: "False"
model_server:
  port: 9991
  host: localhost
  gemini_model_endpoint:
    gemini_flash:
      gemini_model: gemini-1.5-flash
      model_endpoint: /gemini_flash_model
      api_key: test
      model_type: 1
    gemini_embedding:
      gemini_model: models/text-embedding-004
      model_endpoint: /gemini_embedding
      api_key: test
      model_type: 0
  ai_suite_model_endpoint:
    gemini_flash:
      provider_type: Chat
      model: gemini-1.5-flash
      model_endpoint: /ai_suite_gemini_flash_model
      api_key: test
      provider_key: googlegenai
    gemini_embedding:
      provider_type: Embedding
      model: text-embedding-005
      model_endpoint: /ai_suite_gemini_embedding
      api_key: test
      provider_key: googlegenai
    gemini_flash_validation:
      provider_type: Validation
      model: gemini-1.5-flash
      model_endpoint: /ai_suite_gemini_flash_model_validation
      api_key: test
      provider_key: googlegenai
    google_genai_rerank:
      provider_type: Rerank
      model: semantic-ranker-512@latest
      model_endpoint: /ai_suite_rerank
      provider_key: googlecloud
      application_credential: /Users/hayde/certs/cloud/google-gen-lang-key.json
      project_id: gen-lang-client-0937262914
