work_dir: "/model_server_home/work"
env_factories:
  factories:
    test:
      - factory: python_di.inject.context_builder.factory_ctx.FactoryCtx
        lazy: "False"
      - factory: python_di.inject.reflectable_ctx.ReflectableCtx
        lazy: "False"
      - factory: drools_py.inject.serialization_ctx.SerializationCtx
        lazy: "False"
model_server:
  port: 9991
  host: 0.0.0.0
  gemini_model_endpoint:
    gemini_flash:
      gemini_model: gemini-1.5-flash
      model_endpoint: /gemini_flash_model
      api_key: {{gemini_api_key}}
      model_type: 1
    gemini_embedding:
      gemini_model: text-embedding-005
      model_endpoint: /gemini_embedding
      api_key: {{gemini_api_key}}
      model_type: 0
  ai_suite_model_endpoint:
    gemini_flash:
      provider_type: Chat
      model: gemini-1.5-flash
      model_endpoint: /ai_suite_gemini_flash_model
      api_key: {{gemini_api_key}}
      provider_key: googlegenai
    gemini_embedding:
      provider_type: Embedding
      model: text-embedding-005
      model_endpoint: /ai_suite_gemini_embedding
      api_key: {{gemini_api_key}}
      provider_key: googlegenai
    gemini_flash_validation:
      provider_type: Validation
      model: gemini-1.5-flash
      model_endpoint: /ai_suite_gemini_flash_model_validation
      api_key: {{gemini_api_key}}
      provider_key: googlegenai
#  hf_model_endpoint:
#    code_llama:
#      hf_model: code_llama
#      model_endpoint: /code_llama
#      pipeline:
#        task: feature-extraction
#        model: codellama/CodeLlama-7b-hf
#      pipeline_kwargs:
#        do_sample: True
#        top_k: 10
#        temperature: 0.1
#        top_p: 0.95
#        num_return_sequences: 1
#        eos_token_id: tokenizer.eos_token_id
#        max_length: 200
#  hf_model_endpoint:
#    code_llama:
#      hf_model: code_llama
#      model_endpoint: /code_llama
#      pipeline:
#        task: text-generation
#        model: codellama/CodeLlama-7b-Instruct-hf
#      pipeline_kwargs:
#        return_text: True
#        max_length: 20000
