services:
  model-server:
    image: ms
    container_name: model-server-container
    ports:
      - "9991:9991"
    environment:
      HF_HOME: /.huggingface
    volumes:
      - type: bind
        source: /Users/hayde/IdeaProjects/drools/model_server/.models
        target: /.huggingface