kafka_consumer_properties:
  timeout: 10
  max_batch: 10
  key_serializer: 'network_architecture_graph.network_architecture_consumers.kafka.kafka_network_architecture_serializers.KafkaNetworkArchitectureDeserializer'
  value_serializer: 'network_architecture_graph.network_architecture_consumers.kafka.kafka_network_architecture_serializers.KafkaNetworkArchitectureDeserializer'
kafka_producer_properties:
  key_serializer: 'network_architecture_graph.network_architecture_consumers.kafka.kafka_network_architecture_serializers.KafkaNetworkArchitectureSerializer'
  value_serializer: 'network_architecture_graph.network_architecture_consumers.kafka.kafka_network_architecture_serializers.KafkaNetworkArchitectureSerializer'
kafka_properties:
  brokers: 'localhost:9094'