# This workflow will install Python dependencies, run tests and lint all support python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pasta

on: [ push, workflow_dispatch ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
       # TODO: Add back 2.7 if possible
       # TODO: Add 3.4 when possible
        os: [ ubuntu-20.04 ]
        python-version: ["3.5.10", "3.6.15", "3.7.12", "3.8.12", "3.9.9"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with setuptools
      run: |
        python setup.py test
